apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mlops-platform
  namespace: argocd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  roles:
  - name: admin
    policies:
    - p, proj:mlops-platform:admin, applications, *, mlops-platform/*, allow