# Content to deploy Kubeflow Pipelines (standalone)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelines-deployment
  namespace: kubeflow-user-example-com
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipelines
  template:
    metadata:
      labels:
        app: pipelines
    spec:
      containers:
        - name: pipelines-container
          image: <kubeflow pipielines image>
          ports:
            - containerPort: 8888
