# Kustomize Plugin Configuration for Kubeflow v1.9.0

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - example # Updated path

# Additional configuration for Kubeflow v1.9.0
namePrefix: kf-
images:
  - name: kubeflow
    newName: gcr.io/kubeflow-images-public/kubeflow
    newTag: v1.9.0

