apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow
  namespace: argocd
spec:
  project: mlops-platform
  source:
    repoURL: https://github.com/kubeflow/manifests.git
    targetRevision: v1.9.0
    path: applications/pipelines/upstream  # ← Kubeflow Pipelines (leve)
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
