apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: mlops-platform
  source:
    repoURL: https://github.com/kubeflow/manifests.git
    path: example/kustomize
    targetRevision: v1.9.0
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeflow
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - Validate=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
